# SPA: React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy de API
[[redirects]]
  from = "/api/*"
  to = "https://astromania-a37r.onrender.com/api/:splat"
  status = 200
  force = true
